Vert.x Core provides an API for parsing command line arguments passed to programs.

It's also able to print help
messages detailing the options available for a command line tool. Even if such features are far from
the Vert.x core topics, this API is used in the `link:unavailable[Launcher]` class that you can use in _fat-jar_
and in the `vertx` command line tools. In addition, it's polyglot (can be used from any supported language) and is
used in Vert.x Shell.

Vert.x CLI provides a model to describe your command line interface, but also a parser. This parser supports
different types of syntax:

* POSIX like options (ie. `tar -zxvf foo.tar.gz`)
* GNU like long options (ie. `du --human-readable --max-depth=1`)
* Java like properties (ie. `java -Djava.awt.headless=true -Djava.net.useSystemProxies=true Foo`)
* Short options with value attached (ie. `gcc -O2 foo.c`)
* Long options with single hyphen (ie. `ant -projecthelp`)

Using the CLI api is a 3-steps process:

1. The definition of the command line interface
2. The parsing of the user command line
3. The query / interrogation

=== Definition Stage

Each command line interface must define the set of options and arguments that will be used. It also requires a
name. The CLI API uses the `link:../dataobjects.html#Option[Option]` and `link:../dataobjects.html#Argument[Argument]` classes to
describe options and arguments:

[source,ruby]
----
require 'vertx/cli'
cli = Vertx::CLI.create("copy").set_summary("A command line interface to copy files.").add_option({
  'longName' => "directory",
  'shortName' => "R",
  'description' => "enables directory support",
  'flag' => true
}).add_argument({
  'index' => 0,
  'description' => "The source",
  'argName' => "source"
}).add_argument({
  'index' => 0,
  'description' => "The destination",
  'argName' => "target"
})

----

As you can see, you can create a new `link:yardoc/Vertx/CLI.html[CLI]` using
`link:yardoc/Vertx/CLI.html#create-class_method[CLI.create]`. The passed string is the name of the CLI. Once created you
can set the summary and description. The summary is intended to be short (one line), while the description can
contain more details. Each option and argument are also added on the `CLI` object using the
`link:yardoc/Vertx/CLI.html#add_argument-instance_method[addArgument]` and
`link:yardoc/Vertx/CLI.html#add_option-instance_method[addOption]` methods.

==== Options

An `link:../dataobjects.html#Option[Option]` is a command line parameter identified by a _key_ present in the user command
line. Options must have at least a long name or a short name. Long name are generally used using a `--` prefix,
while short names are used with a single `-`. Options can get a description displayed in the usage (see below).
Options can receive 0, 1 or several values. An option receiving 0 values is a `flag`, and must be declared using
`link:../dataobjects.html#Option#set_flag-instance_method[flag]`. By default, options receive a single value, however, you can
configure the option to receive several values using `link:../dataobjects.html#Option#set_multi_valued-instance_method[multiValued]`:

[source,ruby]
----
require 'vertx/cli'
cli = Vertx::CLI.create("some-name").set_summary("A command line interface illustrating the options valuation.").add_option({
  'longName' => "flag",
  'shortName' => "f",
  'flag' => true,
  'description' => "a flag"
}).add_option({
  'longName' => "single",
  'shortName' => "s",
  'description' => "a single-valued option"
}).add_option({
  'longName' => "multiple",
  'shortName' => "m",
  'multiValued' => true,
  'description' => "a multi-valued option"
})

----

Options can be marked as mandatory. A mandatory option not set in the user command line throws an exception during
the parsing:

[source,ruby]
----
require 'vertx/cli'
cli = Vertx::CLI.create("some-name").add_option({
  'longName' => "mandatory",
  'required' => true,
  'description' => "a mandatory option"
})

----

Non-mandatory options can have a _default value_. This value would be used if the user does not set the option in
the command line:

[source,ruby]
----
require 'vertx/cli'
cli = Vertx::CLI.create("some-name").add_option({
  'longName' => "optional",
  'defaultValue' => "hello",
  'description' => "an optional option with a default value"
})

----

An option can be _hidden_ using the `link:../dataobjects.html#Option#set_hidden-instance_method[hidden]` method. Hidden option are
not listed in the usage, but can still be used in the user command line (for power-users).

If the option value is contrained to a fixed set, you can set the different acceptable choices:

[source,ruby]
----
require 'vertx/cli'
cli = Vertx::CLI.create("some-name").add_option({
  'longName' => "color",
  'defaultValue' => "green",
  'choices' => [
    "blue",
    "red",
    "green"
  ],
  'description' => "a color"
})

----

Options can also be instantiated from their JSON form.

==== Arguments

Unlike options, arguments do not have a _key_ and are identified by their _index_. For example, in
`java com.acme.Foo`, `com.acme.Foo` is an argument.

Arguments do not have a name, there are identified using a 0-based index. The first parameter has the
index `0`:

[source,ruby]
----
require 'vertx/cli'
cli = Vertx::CLI.create("some-name").add_argument({
  'index' => 0,
  'description' => "the first argument",
  'argName' => "arg1"
}).add_argument({
  'index' => 1,
  'description' => "the second argument",
  'argName' => "arg2"
})

----

If you don't set the argument indexes, it computes it automatically by using the declaration order.

[source,ruby]
----
require 'vertx/cli'
cli = Vertx::CLI.create("some-name").add_argument({
  'description' => "the first argument",
  'argName' => "arg1"
}).add_argument({
  'description' => "the second argument",
  'argName' => "arg2"
})

----

The `argName` is optional and used in the usage message.

As options, `link:../dataobjects.html#Argument[Argument]` can:

* be hidden using `link:../dataobjects.html#Argument#set_hidden-instance_method[hidden]`
* be mandatory using `link:../dataobjects.html#Argument#set_required-instance_method[required]`
* have a default value using `link:../dataobjects.html#Argument#set_default_value-instance_method[defaultValue]`
* receive several values using `link:../dataobjects.html#Argument#set_multi_valued-instance_method[multiValued]` - only the last argument
can be multi-valued.

Arguments can also be instantiated from their JSON form.

==== Usage generation

Once your `link:yardoc/Vertx/CLI.html[CLI]` instance is configured, you can generate the _usage_ message:

[source,ruby]
----
require 'vertx/cli'
cli = Vertx::CLI.create("copy").set_summary("A command line interface to copy files.").add_option({
  'longName' => "directory",
  'shortName' => "R",
  'description' => "enables directory support",
  'flag' => true
}).add_argument({
  'index' => 0,
  'description' => "The source",
  'argName' => "source"
}).add_argument({
  'index' => 0,
  'description' => "The destination",
  'argName' => "target"
})

builder = Java::JavaLang::StringBuilder.new()
cli.usage(builder)

----

It generates an usage message like this one:

[source]
----
Usage: copy [-R] source target

A command line interface to copy files.

  -R,--directory   enables directory support
----

If you need to tune the usage message, check the `link:unavailable[UsageMessageFormatter]` class.

=== Parsing Stage

Once your `link:yardoc/Vertx/CLI.html[CLI]` instance is configured, you can parse the user command line to evaluate
each option and argument:

[source,ruby]
----
commandLine = cli.parse(userCommandLineArguments)

----

The `link:yardoc/Vertx/CLI.html#parse-instance_method[parse]` method returns a `link:yardoc/Vertx/CommandLine.html[CommandLine]`
object containing the values. By default, it validates the user command line and checks that each mandatory options
and arguments have been set as well as the number of values received by each option. You can disable the
validation by passing `false` as second parameter of `link:yardoc/Vertx/CLI.html#parse-instance_method[parse]`.
This is useful if you want to check an argument or option is present even if the parsed command line is invalid.

You can check whether or not the
`link:yardoc/Vertx/CommandLine.html[CommandLine]` is valid using `link:yardoc/Vertx/CommandLine.html#is_valid-instance_method[isValid]`.

=== Query / Interrogation Stage

Once parsed, you can retrieve the values of the options and arguments from the
`link:yardoc/Vertx/CommandLine.html[CommandLine]` object returned by the `link:yardoc/Vertx/CLI.html#parse-instance_method[parse]`
method:

[source,ruby]
----
commandLine = cli.parse(userCommandLineArguments)
opt = commandLine.get_option_value("my-option")
flag = commandLine.flag_enabled?("my-flag")
arg0 = commandLine.get_argument_value(0)

----

One of your option can have been marked as "help". If a user command line enabled a "help" option, the validation
won't failed, but give you the opportunity to check if the user asks for help:

[source,ruby]
----
require 'vertx/cli'
cli = Vertx::CLI.create("test").add_option({
  'longName' => "help",
  'shortName' => "h",
  'flag' => true,
  'help' => true
}).add_option({
  'longName' => "mandatory",
  'required' => true
})

line = cli.parse(Java::JavaUtil::Collections.singleton_list("-h"))

# The parsing does not fail and let you do:
if (!line.valid?() && line.asking_for_help?())
  builder = Java::JavaLang::StringBuilder.new()
  cli.usage(builder)
  stream.print(builder.to_string())
end

----

