== Using the file system with Vert.x

The Vert.x `link:yardoc/Vertx/FileSystem.html[FileSystem]` object provides many operations for manipulating the file system.

There is one file system object per Vert.x instance, and you obtain it with `link:yardoc/Vertx/Vertx.html#file_system-instance_method[fileSystem]`.

A blocking and a non blocking version of each operation is provided.

The non blocking versions take a handler which is called when the operation completes or an error occurs.

Here's an example of asynchronously copying a file:

[source,ruby]
----
todo:implement-code-translation-for-ruby
----

The blocking versions are named  and return the results or throw exceptions directly.


In many cases, depending on the operating system and file system,some of the potentially blocking operations
can return quickly, which is why we provide them, but it's highly recommended that you test how long they take to
return in your particular application before using them from an event loop, so as not to break the Golden Rule.

Here's the copy using the blocking API:

[source,ruby]
----
todo:implement-code-translation-for-ruby
----

Many operations exist to copy, move, truncate, chmod and many other file operations.

We won't list them all here, please consult the `link:yardoc/Vertx/FileSystem.html[API docs]` for the full list.

=== Asynchronous files

Vert.x provides an asynchronous file abstraction that allows you to manipulate a file on the file system

You open an `link:yardoc/Vertx/AsyncFile.html[AsyncFile]` as follows:

[source,ruby]
----
todo:implement-code-translation-for-ruby
----



TODO